<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Product;
use App\Models\Category;
use Illuminate\Support\Str;
use Illuminate\Support\Facades\DB; // For transaction and raw queries if needed

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $productsData = [
            [
                "id" => 7,
                "name" => "Gannomix Cappuccino",
                "slug" => "gannomix-cappuccino",
                "sku" => "8086",
                "description" => "Esta deliciosa fórmula está diseñada para elevar tu vitalidad, mejorar la circulación y fortalecer tu sistema inmunológico. Gracias a sus antioxidantes, combate los radicales libres y favorece una digestión óptima. Disfruta de una bebida que te revitaliza, te llena de energía y te ayuda a mantenerte saludable todo el día.",
                "short_description" => "Esta deliciosa fórmula está diseñada para elevar tu vitalidad, mejorar la circulación y fortalecer tu sistema inmunológico. ",
                "product_type" => "simple",
                "base_price" => "35.65",
                "points_value" => 20,
                "is_active" => true,
                "category_name" => "Suplemento Nutricional", // Changed from category_id for lookup
                "main_image_path" => "products/main_images/01JVJPZQP0SYAM4FESBQAW8HWD.png",
                "ingredients" => "Chocolate, leche, ganoderma, chaga.",
                "properties" => "Mejora la función cardiovascular, aporte de calcio, reduce la presión arterial, aumenta las defensas.",
                "content_details" => "600 g (30 sobres de 20 g) / Polvo",
                "is_on_promotion" => false,
                "promotional_price" => null,
                "promotion_start_date" => null,
                "promotion_end_date" => null,
                "pays_bonus" => false,
                "bonus_amount" => "0.00",
                "min_configurable_items" => 1,
                "max_configurable_items" => null,
            ],
            [
                "id" => 8,
                "name" => "Digestive Tea",
                "slug" => "digestive-tea",
                "sku" => "8087",
                "description" => "Mejora la digestión y nutre tu organismo con los beneficios que tu sistema digestivo necesita. Alivia y optimiza el proceso digestivo, promoviendo una salud gastrointestinal excelente.",
                "short_description" => "Mejora la digestión y nutre tu organismo con los beneficios que tu sistema digestivo necesita.",
                "product_type" => "simple",
                "base_price" => "31.30",
                "points_value" => 20,
                "is_active" => true,
                "category_name" => "Sistema Digestivo y Metabólico",
                "main_image_path" => "products/main_images/01JVJQ5HV621170CM795XDME96.png",
                "ingredients" => "orégano, galéndula, menta, linaza, manzanilla, jengibre, chía, hierba luisa, cedrón, papaya, pitahaya, anís chiquito.",
                "properties" => "Alivia problemas digestivos, promueve la regeneración de tejido, alivia la indigestión, promueve una sensación de saciedad, alivia la acidez estomacal, alivia problemas gastrointestinales, mejora la salud digestiva, tónico digestivo eficiente, ayuda a la digestión, alivia el malestar digestivo, previene el estreñimiento, reduce síntomas del síndrome de color irritable. ",
                "content_details" => "800 g (20 fundas de té 40 g)",
                "is_on_promotion" => false,
                "promotional_price" => null,
                "promotion_start_date" => null,
                "promotion_end_date" => null,
                "pays_bonus" => false,
                "bonus_amount" => "0.00",
                "min_configurable_items" => 1,
                "max_configurable_items" => null,
            ],
            [
                "id" => 1,
                "name" => "Fiber Mix",
                "slug" => "fiber-mix",
                "sku" => "8080",
                "description" => "Te ayuda a controlar el peso, mejorar la digestión y revitalizar tu organismo. Con su acción de limpieza profunda, previene el acumulamiento de toxinas y bloquea las grasas, dejándote sentir más ligero y saludable. ",
                "short_description" => "Te ayuda a controlar el peso, mejorar la digestión y revitalizar tu organismo. ",
                "product_type" => "simple",
                "base_price" => "35.65",
                "points_value" => 20,
                "is_active" => true,
                "category_name" => "Sistema Digestivo y Metabólico",
                "main_image_path" => "products/main_images/01JVJN0WFSZX5HHH0BQMS943M2.png",
                "ingredients" => "Oligofructosa, Arándanos,  Linaza, Psyllium,Chia, Alcachofa, Flor de Jamaica.",
                "properties" => " Mejora la absorción de minerales en el intestino. Bajo contenido calórico y alto contenido de fibra. Mejora la salud digestiva y baja el colesterol. Controla los niveles de azúcar en la sangre. Es rica en fibra, mejora la salud digestiva. Promueve una digestión saludable. Es un diurético natural y suave.",
                "content_details" => "300 g (30 sobres de 10g) / Polvo",
                "is_on_promotion" => false,
                "promotional_price" => null,
                "promotion_start_date" => null,
                "promotion_end_date" => null,
                "pays_bonus" => false,
                "bonus_amount" => "0.00",
                "min_configurable_items" => 1,
                "max_configurable_items" => null,
            ],
            [
                "id" => 2,
                "name" => "Morinda ASP",
                "slug" => "morinda-asp",
                "sku" => "8081",
                "description" => "Ayuda a tu cuerpo a mantenerse en su mejor forma. Este poderoso suplemento potencia tu sistema inmunológico, proporcionando los nutrientes clave que tu cuerpo necesita para resistir y recuperarse. Siente la vitalidad y energía necesarias para enfrentar cualquier reto, ¡y vive con la confianza de estar protegido en todo momento!",
                "short_description" => "Ayuda a tu cuerpo a mantenerse en su mejor forma.",
                "product_type" => "simple",
                "base_price" => "41.74",
                "points_value" => 20,
                "is_active" => true,
                "category_name" => "Sistema Inmunológico",
                "main_image_path" => "products/main_images/01JVJNK00QTBKMCMBVBGN5GM5A.png",
                "ingredients" => "Sábila, Guánabana, Magnesio, Nogal, Morinda, Noni.",
                "properties" => "Propiedades antioxidantes y cicatrizantes. Combate las radicales libres. Primera línea de defensa del sistema inmunológico, lucha contra las enfermedades bacterianas, previene el cáncer. ",
                "content_details" => "600 ml (30 sobres de 20 ml) / Liquido",
                "is_on_promotion" => false,
                "promotional_price" => null,
                "promotion_start_date" => null,
                "promotion_end_date" => null,
                "pays_bonus" => false,
                "bonus_amount" => "0.00",
                "min_configurable_items" => 1,
                "max_configurable_items" => null,
            ],
            [
                "id" => 3,
                "name" => "L&M Plus",
                "slug" => "lm-plus",
                "sku" => "8082",
                "description" => "Desde una energía renovada hasta una concentración inquebrantable, este producto te impulsa hacia un bienestar integral. Siente cómo tu mente se enfoca y tu cuerpo gana fuerza, alcanzando nuevas alturas físicas y mentales. ",
                "short_description" => "Desde una energía renovada hasta una concentración inquebrantable, este producto te impulsa hacia un bienestar integral. ",
                "product_type" => "simple",
                "base_price" => "35.65",
                "points_value" => 20,
                "is_active" => true,
                "category_name" => "Sistema Nervioso",
                "main_image_path" => "products/main_images/01JVJNRMSJQVRF7Q7WYHYNDQ1T.png",
                "ingredients" => "Maca, Manzana, Romero, Frutilla, Mora, Ginko biloba, Clavo del olor, Remolacha.",
                "properties" => "Protege las células cerebrales contra el estrés oxidativo, proporciona un impulso de energía y concentración, aumenta el suministro de oxígeno al cerebro, mejora la memoria a corto y largo plazo, alivia los síntomas de la demencia, reduce la inflamación cerebral, reduce la presión arterial.",
                "content_details" => "450 ml (30 sobres de 15 ml) / Liquido",
                "is_on_promotion" => false,
                "promotional_price" => null,
                "promotion_start_date" => null,
                "promotion_end_date" => null,
                "pays_bonus" => false,
                "bonus_amount" => "0.00",
                "min_configurable_items" => 1,
                "max_configurable_items" => null,
            ],
            [
                "id" => 4,
                "name" => "Collagen ASP",
                "slug" => "collagen-asp",
                "sku" => "8083",
                "description" => "Nuestra fórmula exclusiva acelera tu metabolismo, mejora tu rendimiento físico y embellece tu piel, dejándola más firme y radiante. Además, fortalece tus articulaciones y huesos, brindándote la vitalidad que necesitas para alcanzar tus metas.",
                "short_description" => "Nuestra fórmula exclusiva acelera tu metabolismo, mejora tu rendimiento físico y embellece tu piel, dejándola más firme y radiante.",
                "product_type" => "simple",
                "base_price" => "51.30",
                "points_value" => 20,
                "is_active" => true,
                "category_name" => "Sistema Músculo - Esquelético",
                "main_image_path" => "products/main_images/01JVJPB0PYCWKTD31GTAZ98YFP.png",
                "ingredients" => "Viatmina E, Glucosamina, Vitamina C, Zinc, Colágeno hidrolizado, Calcio.",
                "properties" => "Antioxidante eficaz que protege las células, reduce el envejecimiento prematuro de la piel, mantiene la elasticidad y la firmeza de la piel, reduce la piel hidratada y saludable, forma y mantiene los huesos fuertes.",
                "content_details" => "600 g (30 sobres de 20 g) / Polvo",
                "is_on_promotion" => false,
                "promotional_price" => null,
                "promotion_start_date" => null,
                "promotion_end_date" => null,
                "pays_bonus" => false,
                "bonus_amount" => "0.00",
                "min_configurable_items" => 1,
                "max_configurable_items" => null,
            ],
            [
                "id" => 5,
                "name" => "Fitness Protein",
                "slug" => "fitness-protein",
                "sku" => "8084",
                "description" => "¡Despierta tu potencial al máximo! Acelera el metabolismo, potencia los músculos y revitaliza todo el cuerpo. ¡Refuerza tu sistema inmunológico y protege el hígado para mantener tu mejor versión!",
                "short_description" => "¡Despierta tu potencial al máximo! ",
                "product_type" => "simple",
                "base_price" => "51.31",
                "points_value" => 20,
                "is_active" => true,
                "category_name" => "Sistema Digestivo y Metabólico",
                "main_image_path" => "products/main_images/01JVJPHBHDDYRCBBBET0K90W2W.png",
                "ingredients" => "Spirulina, calostro, bovino,protína de huevo, quinua, amaranto.",
                "properties" => "Rica en minerales, antioxidantes y vitaminas, contienes anticuerpos contra infecciones, reconstruye y repara el tejido muscular, transporta el oxígeno a los músculos, rica en proteínas, minerales y vitaminas naturales: A, B, c, B1, B2, B3.",
                "content_details" => "600 g (30 sobres de 20 g) / Polvo",
                "is_on_promotion" => false,
                "promotional_price" => null,
                "promotion_start_date" => null,
                "promotion_end_date" => null,
                "pays_bonus" => false,
                "bonus_amount" => "0.00",
                "min_configurable_items" => 1,
                "max_configurable_items" => null,
            ],
            [
                "id" => 6,
                "name" => "Ganoderma Coffee Black",
                "slug" => "ganoderma-coffee-black",
                "sku" => "8085",
                "description" => "No solo fortalece tu sistema inmunológico, sino que también estimula tu sistema nervioso, refuerza tus defensas y mejora la circulación. Además, favorece la digestión, ayudando a tu cuerpo a funcionar de manera óptima. Disfruta de una taza que te brinda salud y energía con cada sorbo.",
                "short_description" => "No solo fortalece tu sistema inmunológico, sino que también estimula tu sistema nervioso, refuerza tus defensas y mejora la circulación.",
                "product_type" => "simple",
                "base_price" => "26.96",
                "points_value" => 15,
                "is_active" => true,
                "category_name" => "Suplemento Nutricional",
                "main_image_path" => "products/main_images/01JVJPSY9364N526SDHCJ00QNB.png",
                "ingredients" => "Chaga, ganoderma, resveratrol.",
                "properties" => "Aumenta las defensas, reduce la presión arterial, reduce la formación de coágulos sanguíneos.",
                "content_details" => "150 g (30 sobres de 5g) / Polvo",
                "is_on_promotion" => false,
                "promotional_price" => null,
                "promotion_start_date" => null,
                "promotion_end_date" => null,
                "pays_bonus" => false,
                "bonus_amount" => "0.00",
                "min_configurable_items" => 1,
                "max_configurable_items" => null,
            ],
            [
                "id" => 9,
                "name" => "Diuretic Tea",
                "slug" => "diuretic-tea",
                "sku" => "8088",
                "description" => "Esta infusión ayuda a eliminar toxinas, optimizando la hidratación y promoviendo una sensación de ligereza. Con sus beneficios naturales, favorece la función renal y mejora el equilibrio del cuerpo.",
                "short_description" => "Esta infusión ayuda a eliminar toxinas, optimizando la hidratación y promoviendo una sensación de ligereza. ",
                "product_type" => "simple",
                "base_price" => "31.30",
                "points_value" => 20,
                "is_active" => true,
                "category_name" => "Sistema Digestivo y Metabólico",
                "main_image_path" => "products/main_images/01JVJQAT1BE2A1E43ASKPZDWBC.png",
                "ingredients" => "té verde, hoja de naranja, ishpingo, cúrcuma, clavo de olor, cola de caballo, hierba buena, maliva olorosa, anís, stevia en hoja, manzanilla, diente de león. ",
                "properties" => "Reduce la retención de líquidos, ayuda en la eliminación de líquidos y toxinas, buena fuente de varios minerales esenciales, reduce la hinchazón y la retención de líquidos. Mantiene un equilibrio adecuado de electrolitos, ayuda a reducir la acumulación de líquidos, aumenta la producción de orina, alivio en casos de inflamción del tracto urinario, constribuye a la deintoxicación del cuerpo, reduce la carga de fluidos en los vasos sanguíneos, alivia la hinchazón y la sensación de pesadez, alivia cuando se produce edemas.",
                "content_details" => "800 g (20 fundas de té 40 g)",
                "is_on_promotion" => false,
                "promotional_price" => null,
                "promotion_start_date" => null,
                "promotion_end_date" => null,
                "pays_bonus" => false,
                "bonus_amount" => "0.00",
                "min_configurable_items" => 1,
                "max_configurable_items" => null,
            ],
            [
                "id" => 10,
                "name" => "Diurens",
                "slug" => "diurens",
                "sku" => "8090",
                "description" => "Te ayuda a vencer la fatiga, fortalecer tus defensas y aliviar los cólicos, ofreciéndote bienestar en cada sorbo. Embárcate en un viaje hacia una versión más fuerte, radiante y llena de vitalidad.",
                "short_description" => "Te ayuda a vencer la fatiga, fortalecer tus defensas y aliviar los cólicos, ofreciéndote bienestar en cada sorbo.",
                "product_type" => "simple",
                "base_price" => "36.66",
                "points_value" => 20,
                "is_active" => true,
                "category_name" => "Sistema Reproductor",
                "main_image_path" => "products/main_images/01JVJQFCKSMHYCHB790RQ70YAA.png",
                "ingredients" => "maca, borojó, licopeno, mashua, ginseng.",
                "properties" => "Reduce los síntomas de los cólicos menstruales, aumenta la energía y la vitalidad, alivia algunos síntomas de la menopausia, potente diurético y depurativo, antioxidante potente.",
                "content_details" => "500 ml (25 sobres de 20 ml) / Liquido",
                "is_on_promotion" => false,
                "promotional_price" => null,
                "promotion_start_date" => null,
                "promotion_end_date" => null,
                "pays_bonus" => false,
                "bonus_amount" => "0.00",
                "min_configurable_items" => 1,
                "max_configurable_items" => null,
            ],
            [
                "id" => 11,
                "name" => "Vhigorth",
                "slug" => "vhigorth",
                "sku" => "8091",
                "description" => "Está especialmente formulado para el cuidado integral masculino, combatiendo el cansancio, promoviendo la salud de la próstata y mejorando tu vitalidad. Siente cómo tu energía aumenta y cada aspecto de tu vida se revitaliza.",
                "short_description" => "Está especialmente formulado para el cuidado integral masculino, combatiendo el cansancio, promoviendo la salud de la próstata y mejorando tu vitalidad.",
                "product_type" => "simple",
                "base_price" => "42.61",
                "points_value" => 20,
                "is_active" => true,
                "category_name" => "Sistema Reproductor",
                "main_image_path" => "products/main_images/01JVJQMD7Z7W70KSMJWD7MA1YQ.png",
                "ingredients" => "Licopeno, maca, mashua, borojó,ginseng.",
                "properties" => "Reduce la probabilidad de tener problemas en la próstata, aumenta el flujo sanguíneo al área genital, previene infecciones de las vías urinarias, aumenta la energía y la vitalidad, antioxidante.",
                "content_details" => "500 ml (25 sobres de 20 ml) / Liquido",
                "is_on_promotion" => false,
                "promotional_price" => null,
                "promotion_start_date" => null,
                "promotion_end_date" => null,
                "pays_bonus" => false,
                "bonus_amount" => "0.00",
                "min_configurable_items" => 1,
                "max_configurable_items" => null,
            ],
            [
                "id" => 12,
                "name" => "Menta Fuerte",
                "slug" => "menta-fuerte",
                "sku" => "8094",
                "description" => "Aumenta tu vitalidad, mejora la circulación y fortalece tu sistema inmunológico. Con potentes antioxidantes, combate los radicales libres y optimiza la digestión, dejándote con una sensación de bienestar total.",
                "short_description" => "Aumenta tu vitalidad, mejora la circulación y fortalece tu sistema inmunológico.",
                "product_type" => "simple",
                "base_price" => "16.52",
                "points_value" => 2,
                "is_active" => true,
                "category_name" => "Cosmetica Biologica",
                "main_image_path" => "products/main_images/01JVJQSAGDHHCD1B91FA9PBP5Q.png",
                "ingredients" => "DMSO Oxígeno limpio, plata coloidal, mentol expectorante, extracto de menta.",
                "properties" => "Reduce la inflamación y bloquea las señales de dolor en los nervios, propiedades antibacterianas , antivirales y antifúngicas, reduce la inflamación en las vías respiratorias, refrescante natural de la respiración.",
                "content_details" => "30ml / Liquido",
                "is_on_promotion" => false,
                "promotional_price" => null,
                "promotion_start_date" => null,
                "promotion_end_date" => null,
                "pays_bonus" => false,
                "bonus_amount" => "0.00",
                "min_configurable_items" => 1,
                "max_configurable_items" => null,
            ],
            [
                "id" => 13,
                "name" => "DermaSLM Gel",
                "slug" => "dermaslm-gel",
                "sku" => "8095",
                "description" => "Este gel está formulado para ayudarte a reducir medidas, reafirmar los tejidos y devolverle a tu piel la hidratación que necesita. Con su efecto tonificante y reafirmante, cada aplicación proporciona frescura y bienestar, dejándote con una piel más suave, tonificada y revitalizada.",
                "short_description" => "Este gel está formulado para ayudarte a reducir medidas, reafirmar los tejidos y devolverle a tu piel la hidratación que necesita. ",
                "product_type" => "simple",
                "base_price" => "17.39",
                "points_value" => 2,
                "is_active" => true,
                "category_name" => "Cosmetica Biologica",
                "main_image_path" => "products/main_images/01JVJQYK22APW5Z4P0DMVBSB64.png",
                "ingredients" => "Alcanfor, Centella asiática, té verde, mentol.",
                "properties" => "Beneficios tonificantes, ayuda a reducir medidas y reafirmar tejidos adiposos, nutre e hidrata la piel, beneficios reductores",
                "content_details" => "500g / Gel",
                "is_on_promotion" => false,
                "promotional_price" => null,
                "promotion_start_date" => null,
                "promotion_end_date" => null,
                "pays_bonus" => false,
                "bonus_amount" => "0.00",
                "min_configurable_items" => 1,
                "max_configurable_items" => null,
            ],
            [
                "id" => 14,
                "name" => "Paquete 140",
                "slug" => "paquete-140",
                "sku" => "9001",
                "description" => "Paquete Multiproductos",
                "short_description" => "Paquete Multiproductos",
                "product_type" => "bundle_fixed",
                "base_price" => "121.74",
                "points_value" => 40,
                "is_active" => true,
                "category_name" => "Paquete Re-consumo y Activaciones",
                "main_image_path" => "products/main_images/01JVJRFPG56P2X7GET4WD0CBY1.png",
                "ingredients" => "Paquete Multiproductos",
                "properties" => "Paquete Multiproductos",
                "content_details" => "5 productos",
                "is_on_promotion" => false,
                "promotional_price" => null,
                "promotion_start_date" => null,
                "promotion_end_date" => null,
                "pays_bonus" => true,
                "bonus_amount" => "30.00",
                "min_configurable_items" => 1, // For fixed bundles, this might not be strictly used in the same way as configurable
                "max_configurable_items" => null,
            ],
            [
                "id" => 15,
                "name" => "Paquete 81",
                "slug" => "paquete-81",
                "sku" => "9002",
                "description" => "Paquete multiproductos x3",
                "short_description" => "Paquete multiproductos x3",
                "product_type" => "bundle_configurable",
                "base_price" => "70.43",
                "points_value" => 40,
                "is_active" => true,
                "category_name" => "Paquete Re-consumo y Activaciones",
                "main_image_path" => "products/main_images/01JVJRN5SVXJ6190BK2RTR65P7.png",
                "ingredients" => "Paquete multiproductos x3",
                "properties" => "Paquete multiproductos x3",
                "content_details" => "Paquete multiproductos x3",
                "is_on_promotion" => false,
                "promotional_price" => null,
                "promotion_start_date" => null,
                "promotion_end_date" => null,
                "pays_bonus" => false,
                "bonus_amount" => "0.00",
                "min_configurable_items" => 3,
                "max_configurable_items" => 3,
            ]
        ];

        DB::transaction(function () use ($productsData) {
            foreach ($productsData as $productData) {
                $category = Category::where('name', $productData['category_name'])->first();

                if (!$category) {
                    $this->command->warn("Categoría '{$productData['category_name']}' no encontrada para el producto '{$productData['name']}'. Saltando este producto.");
                    continue;
                }

                // Ensure slug is unique if not provided or to prevent issues
                $slug = $productData['slug'] ?? Str::slug($productData['name']);
                $originalSlug = $slug;
                $counter = 1;
                while (Product::where('slug', $slug)->where('id', '!=', $productData['id'] ?? null)->exists()) {
                    $slug = $originalSlug . '-' . $counter++;
                }
                
                // Prepare data for updateOrCreate
                $dataToInsert = [
                    'name' => $productData['name'],
                    'slug' => $slug,
                    'sku' => $productData['sku'] ?? null,
                    'description' => $productData['description'] ?? null,
                    'short_description' => $productData['short_description'] ?? null,
                    'product_type' => $productData['product_type'] ?? 'simple',
                    'base_price' => $productData['base_price'] ?? 0.00,
                    'points_value' => $productData['points_value'] ?? 0,
                    'is_active' => $productData['is_active'] ?? true,
                    'category_id' => $category->id,
                    'main_image_path' => $productData['main_image_path'] ?? null,
                    'ingredients' => $productData['ingredients'] ?? null,
                    'properties' => $productData['properties'] ?? null,
                    'content_details' => $productData['content_details'] ?? null,
                    'is_on_promotion' => $productData['is_on_promotion'] ?? false,
                    'promotional_price' => $productData['promotional_price'] ?? null,
                    'promotion_start_date' => $productData['promotion_start_date'] ?? null,
                    'promotion_end_date' => $productData['promotion_end_date'] ?? null,
                    'pays_bonus' => $productData['pays_bonus'] ?? false,
                    'bonus_amount' => $productData['bonus_amount'] ?? '0.00',
                    'min_configurable_items' => $productData['min_configurable_items'] ?? null,
                    'max_configurable_items' => $productData['max_configurable_items'] ?? null,
                    // 'created_at' and 'updated_at' will be handled by Eloquent
                ];

                // Use updateOrCreate based on SKU if available and unique, otherwise use name or slug.
                // For simplicity here, we'll use SKU as the primary lookup, then slug.
                // If you want to preserve existing IDs, this logic would need to be more complex
                // or you'd run `php artisan migrate:fresh --seed` which is often safer for seeders.

                $lookupKey = [];
                if (!empty($productData['sku'])) {
                    $lookupKey = ['sku' => $productData['sku']];
                } elseif (!empty($slug)) {
                    $lookupKey = ['slug' => $slug]; // Use the potentially modified unique slug
                } else {
                     $this->command->warn("Producto '{$productData['name']}' no tiene SKU ni Slug. Saltando.");
                    continue;
                }
                
                Product::updateOrCreate($lookupKey, $dataToInsert);
            }
        });

        $this->command->info(count($productsData) . ' productos han sido procesados por el seeder.');
        $this->command->info('NOTA: Este seeder no maneja las relaciones de bundles (fixed/configurable) ni los precios específicos por país (product_prices). Esos deben manejarse por separado si es necesario.');
    }
}
